# -*- coding: utf-8 -*-
"""PC2-Macro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0faWvLPne3ooqBVvtYVYNfmYOBk3UNu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("csv_limpio.csv")

df.columns

df.head(5)

"""# Consulta 1 - Agrupamientos

## ¿Cuál es la cantidad de sedes aeroportuerias y la suma de sus códigos de provincia agrupadas por departamento, tipo de aeródromo y estado operativo?
"""

c_1_1 = df.groupby(["DEPARTAMENTO", "TIPO_AERODROMO", "ESTADO"]).agg(
      {"ID_AERODROMO": "count",
      "ID_PROVINCIA": "sum"}
).reset_index()
c_1_1.columns = ['Departamento', 'Tipo', 'Estado', 'Cantidad_Sedes', 'Suma_ID_Prov']
c_1_1

plt.figure(figsize=(6,4))
sns.barplot(data=c_1_1.head(15), x="Departamento", y="Cantidad_Sedes", hue="Tipo")
plt.title("Gráfico 1: Análisis de Sedes por Región, Tipo y Estado")
plt.xticks(rotation=45)
plt.show()

"""## ¿Cuál es el conteo de infraestructuras y la suma de sus códigos de distrito segmentados por la entidad administradora, su nivel de jerarquía y el tipo de titularidad?"""

c_1_2 = df.groupby(["ADMINISTRADOR", "JERARQUIA", "TITULARIDAD"]).agg({
    "ID_AERODROMO": "count",
    "ID_DISTRITO": "sum"
}).reset_index()
c_1_2.columns = ["Administrador","Jerarquia","Titularidad","Nro. Sedes","Sum_Id_Dist"]
c_1_2

plt.figure(figsize=(6,4))
sns.barplot(data=c_1_2.sort_values("Sum_Id_Dist", ascending=False).head(15),
            x="Administrador", y="Sum_Id_Dist", hue="Jerarquia")
plt.title("Gráfico 2: Análisis de Gestión por Administrador, Jerarquía y Titularidad")
plt.xticks(rotation=45)
plt.show()

"""# Consulta 2

## Generación de 3 nuevas columnas, extrayendo o transformando los datos de las columnas actuales, mencionando cuál será su futuro uso

### Columna 1 - Macroregiones

Permitirá comparar la densidad de aeródromos en la selva frente a la Costa y Sierra, sin la necesidad de comparar departamento por departamento
"""

def asignar_macroregion(depart):
  selva = ['LORETO', 'UCAYALI', 'AMAZONAS', 'MADRE DE DIOS', 'SAN MARTÍN']
  sierra = ['CUSCO', 'PUNO', 'APURÍMAC', 'HUÁNUCO', 'PASCO', 'JUNÍN', 'AYACUCHO', 'HUANCAVELICA']
  if depart in selva: return 'SELVA'
  elif depart in sierra: return 'SIERRA'
  else: return 'COSTA'

df["MACROREGION"] = df["DEPARTAMENTO"].apply(asignar_macroregion)

df.head(5)

"""### Columna 2 - SITUACION LEGAL

Se usará para hacerlo en gráficos circulares y barras apiladas en la gestión de la infraestructura, esto permitiá que los aeropuertos no se mezclen erroneamente como el aeropuerto de andahuaylas que aún no ha sido entregado, y permite un análisis de la seguridad jurídica de la infraestructura
"""

def categorizar_conse(conse):
  if conse==1:
    return "Concesionada"
  elif conse==9:
    return "Concesionada (Pendiente de Entrega)"
  elif conse==-1:
    return "Privada (No aplica)"
  else:
    return "Pública (No Concesionada)"

df["SITUACION_LEGAL"] = df["ES_CONCES"].apply(categorizar_conse)

df.head(10)

"""### Columna 3 - AÑO

Servirá como eje X en los Gráficos de Lineas y Tendencias Acumulativas para así visualizar la evolución del inventario de aeródromos a los largo de los años (2022-2024)
"""

df["ANIO_CORTE"] = df["FECHA_CORTE"].astype(str).str[:4]

df.head(10)

"""# Consulta 3

## Implementación de matriz de correlación de al menos 6 columnas usando seaborn e interpretar
"""

df.columns

df.dtypes

"""### ¿Existe una relación estadística entre la ubicación geográfica (Latitud/Longitud), la codificación política (IDs de Departamento/Provincia) y el estado de concesión de la infraestructura?"""

# Usaremos las columnas que son de campo numérico
use_columns = [
    'ID_DEPARTAMENTO',
    'ID_PROVINCIA',
    'ID_DISTRITO',
    'LATITUD',
    'LONGITUD',
    'ES_CONCES'
]

df_corr = df[use_columns].corr()

plt.figure(figsize=(6,4))
sns.heatmap(df_corr, annot=True, cmap='coolwarm')
plt.title("Matriz de correlación")
plt.show()

"""# Consulta 4

### Grafico 1 - ¿Cómo se distribuyen los diferentes tipos de Infraestructura (Aeródromo, Aeropuerto, Helipuerto) en cada Macroregión según su estado operativo?
"""

c_4_1 = df.groupby(["MACROREGION", "TIPO_AERODROMO", "ESTADO"]).size().reset_index(name = "CONTEO")
c_4_1

plt.figure(figsize=(6,4))
sns.barplot(data=c_4_1, x="MACROREGION", y="CONTEO", hue="TIPO_AERODROMO")
plt.title("Gráfico 1: Infraestructura por Macroregión y Estado")
plt.xlabel("Macroregión")
plt.ylabel("Nro. Sedes")
plt.legend(title="Tipo Infraestructura", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.show()

"""### Gráfico 2 - Cuál es la cantidad de sedes administradas por CORPAC u otros entes, según su jerarquía (Nacional/Regional) y su situación legal (Concesionada/Privada)?"""

c_4_2 = df["ADMINISTRADOR"].value_counts().nlargest(5).index
c_4_2 = df[df["ADMINISTRADOR"].isin(c_4_2)]
c_4_2=c_4_2.groupby(["ADMINISTRADOR", "JERARQUIA", "SITUACION_LEGAL"]).size().reset_index(name = "TOTAL")
c_4_2

plt.figure(figsize=(6,4))
sns.barplot(data=c_4_2, x="ADMINISTRADOR", y="TOTAL", hue="JERARQUIA", palette="viridis")
plt.title("Gráfico 2: Gestión por Administrador, Jerarquía y Situación Legal")
plt.xlabel("Administrador")
plt.ylabel("Nro. Sedes")
plt.xticks(rotation=30, ha='right')
plt.legend(title="Jerarquía", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""# Consulta 5

### Gráfico 1: ¿Cómo ha evolucionado la cantidad de registros de infraestructura aeroportuaria en las tres Macroregiones (Costa, Sierra, Selva) a través de los años de corte?
"""

c_5_1 = df.groupby(["ANIO_CORTE", "MACROREGION", "TIPO_AERODROMO"]).size().reset_index(name="CONTEO")
c_5_1["ANIO_CORTE"] = c_5_1["ANIO_CORTE"].astype(str)

plt.figure(figsize=(10,4))
sns.lineplot(data=c_5_1, x="ANIO_CORTE", y="CONTEO", hue="MACROREGION", style="MACROREGION", markers=True, markersize=10, linewidth=2)
plt.title("Gráfico 1: Evolución de Sedes por Macroregión y Tipo (2022-2024)")
plt.xlabel("Año de Corte")
plt.ylabel("Nro. Sedes")
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend(title="Macroregion/Tipo", bbox_to_anchor=(1.05,1), loc="upper left")
plt.tight_layout()
plt.show()

"""### Gráfico 2: ¿Cuál es la tendencia anual del número de infraestructuras según su Situación Legal (Concesionada, Privada, etc) y su nivel de Jerarquía?"""

c_5_2 = df.groupby(["ANIO_CORTE", "SITUACION_LEGAL", "JERARQUIA"]).size().reset_index(name="TOTAL")
c_5_2["ANIO_CORTE"]=c_5_2["ANIO_CORTE"].astype(str)

plt.figure(figsize=(10,4))
sns.lineplot(data=c_5_2, x="ANIO_CORTE", y="TOTAL", hue="SITUACION_LEGAL", marker="o", markersize=8, linewidth=2.5)
plt.title("Gráfico 2: Tendencia de Situación Legal de la Infraestructura")
plt.xlabel("Año de Corte")
plt.ylabel("Nro. Sedes")
plt.grid(True, linestyle=":", alpha=0.7)
plt.legend(title="Situación Legal", bbox_to_anchor=(1.05,1), loc="upper left")
plt.tight_layout()
plt.show()

"""# Consulta 6

### ¿Cómo ha crecido el registro total acumulado de infraestructuras en cada Macroregion (Costa, Sierra, Selva) a través de los años?
"""

c_6_1=df.groupby(["ANIO_CORTE", "MACROREGION"]).size().reset_index(name="CONTEO")
c_6_1["ACUMULADO"]=c_6_1.groupby("MACROREGION")["CONTEO"].cumsum()
c_6_1

plt.figure(figsize=(6,4))
for region in c_6_1["MACROREGION"].unique():
    datos_region = c_6_1[c_6_1["MACROREGION"] == region]
    plt.plot(datos_region["ANIO_CORTE"].astype(str), datos_region["ACUMULADO"], marker='o', label=region)

plt.title("Gráfico 1: Evolución Acumulada de Sedes por Macroregión")
plt.xlabel("Año de Corte")
plt.ylabel("Sedes Acumuladas")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""### ¿Cuál es el crecimiento acumulativo de la infraestructura según su Situación Legal (Privada, Concesionada, Pública) en los periodos reportados?"""

c_6_2 = df.groupby(['ANIO_CORTE', 'SITUACION_LEGAL']).size().reset_index(name='CONTEO')

c_6_2['ACUMULADO'] = c_6_2.groupby('SITUACION_LEGAL')['CONTEO'].cumsum()

plt.figure(figsize=(10, 5))
for situacion in c_6_2["SITUACION_LEGAL"].unique():
    datos_sit = c_6_2[c_6_2["SITUACION_LEGAL"] == situacion]
    plt.plot(datos_sit["ANIO_CORTE"].astype(str), datos_sit["ACUMULADO"], marker='s', label=situacion)

plt.title("Gráfico 2: Crecimiento Acumulado según Situación Legal")
plt.xlabel("Año de Corte")
plt.ylabel("Total Acumulado")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""### ¿Cómo se acumula el total de activos registrados en el país diferenciado por Tipo (Aeródromo vs Aeropuerto)?"""

c_6_3 = df.groupby(['ANIO_CORTE', 'TIPO_AERODROMO']).size().reset_index(name='CONTEO')
c_6_3['ACUMULADO'] = c_6_3.groupby('TIPO_AERODROMO')['CONTEO'].cumsum()
c_6_3

plt.figure(figsize=(10, 5))
tipos_principales = ['Aeródromo', 'Aeropuerto', 'Helipuerto', "Aeropuerto Internacional", "Helipuerto Elevado", "Helipuerto de superficie"]
for tipo in tipos_principales:
    if tipo in c_6_3["TIPO_AERODROMO"].unique():
        datos_tipo = c_6_3[c_6_3["TIPO_AERODROMO"] == tipo]
        plt.plot(datos_tipo["ANIO_CORTE"].astype(str), datos_tipo["ACUMULADO"], marker='^', label=tipo)

plt.title("Gráfico 3: Tendencia Acumulativa por Tipo de Infraestructura")
plt.xlabel("Año de Corte")
plt.ylabel("Cantidad Acumulada")
plt.legend()
plt.show()

"""# Consulta 7

### Gráfico 1: ¿Cuál es la proporción de los diferentes tipos de infraestructura (Aeródromos, Helipuertos, etc) especificamente en la Selva?
"""

c_7_1 = df[df["MACROREGION"] == "SELVA"].groupby("TIPO_AERODROMO").size()

plt.figure(figsize=(8, 6))
etiquetas = c_7_1.index

plt.pie(c_7_1, labels=etiquetas, autopct="%1.1f%%", startangle=140, colors=sns.color_palette("Set2"))
plt.title("Gráfico 1: Distribución de Infraestructura en la SELVA")
plt.show()

"""### ¿Cómo se divide el nivel de importancia (Jerarquía) de las sedes ubicadas únicamente en la costa?"""

c_7_2 = df[df["MACROREGION"] == "COSTA"].groupby("JERARQUIA").size()

plt.figure(figsize=(8, 6))
etiquetas_jer = c_7_2.index

plt.pie(c_7_2, labels=etiquetas_jer, autopct="%1.1f%%", startangle=90, colors=sns.color_palette("Pastel1"))
plt.title("Gráfico 2: Distribución de Jerarquías en la COSTA")
plt.show()

"""# Guardar nuevo csv"""

df.to_csv("csv_nuevo.csv", index=False, encoding="utf-8-sig")

